name = "TetraGrayer"
version = "0.1.0"
defaultTargets = ["tetragrayer"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = true
# prevent confusing the AI with missing identifiers misidentified as implicit arguments
relaxedAutoImplicit = false
linter.missingDocs = true
doc.verso = true


[[lean_lib]]
name = "TetraGrayer"
glob = ["TetraGrayer.*"]

[[lean_exe]]
name = "tetragrayer"
root = "Main"
